{% set name = "jax" %}
{% set version = "0.3.18" %}

package:
  name: jax
  version: {{ version }}

source:
  # only pull source after PyPI release.
  url: https://pypi.io/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: 8a1a265c671f0770637c95b32d1c5b2af2c85b2f922a0fcdde1177d4e11b296e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - absl-py
    - numpy >=1.20
    - opt_einsum
    - scipy >=1.5
    - typing_extensions
    # Not declared in the metadata but essential to this package.
    # update minimum from https://github.com/google/jax/blob/main/jax/version.py#L21
    - jaxlib >=0.3.14
    # new dep etils[epath] and its needs:
    - etils
    - importlib_resources
    - zipp

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
    - ngam
