{% set version = "0.3.10" %}

package:
  name: jax
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: 87aaa7a9708ee12ad3efb0b0feaa8873ed209750b256cc9b9a8fa1e3c1ede69c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - absl-py
    - numpy >=1.18
    - opt_einsum
    - scipy >=1.2.1
    - typing_extensions
    # Not declared in the metadata but essential to this package.
    - jaxlib

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
