{% set version = "0.2.24" %}

package:
  name: jax
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: ad09da2fad41121a4c0bbb15d548f4349dd0f1d6ef90fc3d7f62139c23a979bb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - absl-py
    - numpy >=1.17
    - opt_einsum
    # Not declared in the metadata but essential to this package.
    - jaxlib

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
