{% set name = "jax" %}
{% set version = "0.4.1" %}

package:
  name: jax
  version: {{ version }}

source:
  # only pull source after PyPI release.
  url: https://pypi.io/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: b795a75ca2eabb5d20b83f1aa1e1038dafeca89ee74c9ac6e2b919215cadf427

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.20
    - opt_einsum
    - scipy >=1.5
    # Not declared in the metadata but essential to this package.
    # update minimum from https://github.com/google/jax/blob/main/jax/version.py#L21
    - jaxlib >=0.3.22

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
    - ngam
