{% set name = "jax" %}
{% set version = "0.3.22" %}

package:
  name: jax
  version: {{ version }}

source:
  # only pull source after PyPI release.
  url: https://pypi.io/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: 3ff3fd28e0f6ccdf9d91a51e2488aecabc86b16cb92a3519b3036d972d970320

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - absl-py
    - numpy >=1.20
    - opt_einsum
    - scipy >=1.5
    - typing_extensions
    # Not declared in the metadata but essential to this package.
    # update minimum from https://github.com/google/jax/blob/main/jax/version.py#L21
    - jaxlib >=0.3.15
    # new dep etils[epath] and its needs:
    - etils
    - importlib_resources
    - zipp

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
    - ngam
